### ISSUE TITLE
avatar problems 1 

### ISSUE THREAD

**Issue by ChenShen1017** [d-abacus/dabacus-org-website#97]
small images should be at the middle of big image, not bottom

<img width="1196" alt="Screen Shot 2021-06-07 at 1 51 46 pm" src="https://user-images.githubusercontent.com/81792317/120965481-8927ad00-c797-11eb-83cd-b22a7e3f950c.png">
<img width="1232" alt="Screen Shot 2021-06-07 at 1 52 05 pm" src="https://user-images.githubusercontent.com/81792317/120965486-8af17080-c797-11eb-9851-15ad0a6e632d.png">

**Comment by ShuaJJ** [comment]
@all-contributors please add @ChenShen1017
