### ISSUE TITLE
avatar problems 2

### ISSUE THREAD

**Issue by ChenShen1017** [d-abacus/dabacus-org-website#98]
1 Maybe we can change the effect condition from hover to click ,  so we need to avatar become clickable mouse
2 After user click the avatar first time, if him click other avatars,  the below content maintain the place, do not up and down  while users clicking(switch) the avatars. If users click any other places( not avatars) , the below content back to the original place

**Comment by ShuaJJ** [comment]
@all-contributors please add @ChenShen1017 for bug
